version: '3.9'
services:
  gameserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "25565:25565"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SERVER_ID: ${SERVER_ID}

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: